// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbMBs8vZjcWCTXax-j3lq_9yKoUSINgJE',
    appId: '1:190804428130:web:bf1b76bb0187c6a9c8583b',
    messagingSenderId: '190804428130',
    projectId: 'poultryerp-2af23',
    authDomain: 'poultryerp-2af23.firebaseapp.com',
    storageBucket: 'poultryerp-2af23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8KZ86wE_LYsd8LfczNDYWsmO_Gq4kT8',
    appId: '1:190804428130:android:e58ef6a0ae9f53fcc8583b',
    messagingSenderId: '190804428130',
    projectId: 'poultryerp-2af23',
    storageBucket: 'poultryerp-2af23.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbMBs8vZjcWCTXax-j3lq_9yKoUSINgJE',
    appId: '1:190804428130:web:1ca383bc4ecabf10c8583b',
    messagingSenderId: '190804428130',
    projectId: 'poultryerp-2af23',
    authDomain: 'poultryerp-2af23.firebaseapp.com',
    storageBucket: 'poultryerp-2af23.firebasestorage.app',
  );
}
